name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-master:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker
        uses: meysam81/build-docker@main
        with:
          cosign: true
          image-extra-tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ github.run_id }}
            ghcr.io/${{ github.repository }}:latest
          image-name: ghcr.io/${{ github.repository }}

  release-please:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - id: release-please
        name: Release please
        uses: googleapis/release-please-action@v4
        with:
          release-type: python

  build-prod:
    needs: release-please
    if: needs.release-please.outputs.releases_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker
        uses: meysam81/build-docker@main
        with:
          cosign: true
          image-extra-tags: |
            ghcr.io/${{ github.repository }}:${{ needs.release-please.outputs.tag_name }}
          image-name: ghcr.io/${{ github.repository }}
          ref: ${{ needs.release-please.outputs.tag_name }}
